### ISSUE TITLE
想问下为啥退出重新进存档 就显示游戏结束过了 必须要开新游戏

### ISSUE THREAD

**Issue by rmm233** [JesKi13567/TimeTrap#1]
RT
因为会打算玩比较久 不会一次肝到打龙 如果可以重进也保留游戏就好了

**Comment by JesKi13567** [comment]
什么版本？不应该啊...你是在服务端开的吗，就有可能一直在计时。

**Comment by rmm233** [comment]
> 



> 什么版本？不应该啊...你是在服务端开的吗，就有可能一直在计时。

啊 刚才重试了一下整明白了 是有朋友在玩的时候调了旁观者模式 然后游戏就自动结束了 是我这边的问题 _(:з」∠)_
感谢作者大大

**Comment by JesKi13567** [comment]
没事，解决了就好awa
