### ISSUE TITLE
单人游戏重进后出现时间不再显示的问题

### ISSUE THREAD

**Issue by rmm233** [JesKi13567/TimeTrap#2]
楼主可以看看我这视频 
链接: https://pan.baidu.com/s/1pyFWWGl1WHOHdlDZTZlUaw?pwd=dp5s 提取码: dp5s 复制这段内容后打开百度网盘手机App，操作更方便哦
重进后时间不显示 输入/reload提示这个存档已经玩过了 
游戏版本1.19.2 带forge 没有安装改变游戏玩法的mod 只安装了 物品信息拓展 和 血量显示 模组及其前置
多次测试发现是会随机出现这个问题 有时候重进是正常的 大部分时候会出问题

**Comment by JesKi13567** [comment]
看到了，你的端是加了mod的，我的数据包是在官方白端/仅安装optifine端环境下是正常的，建议使用上述的环境进行游戏。mod造成的问题与本数据包无关。

**Comment by rmm233** [comment]
> 看到了，你的端是加了mod的，我的数据包是在官方白端/仅安装optifine端环境下是正常的，建议使用上述的环境进行游戏。mod造成的问题与本数据包无关。

我把forge去掉了 只有optfine 同样出现此问题
链接: https://pan.baidu.com/s/1nPdDruH8Su_Vw6jGJ56arQ?pwd=u72v 提取码: u72v 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by JesKi13567** [comment]
我找到原因了，就是forge端的问题，我甚至用fabric都没事，万恶之源forge，高版本建议使用fabric。

**Comment by JesKi13567** [comment]
刚刚更新了下评论，如果解决了回复一下qwq

**Comment by rmm233** [comment]
我又试了试 用了pcl启动器 这次连optfine都没装 好像跟forge也没关系 同样也有问题 我的java是17.0.3 我升级试试

**Comment by rmm233** [comment]
> 我又试了试 用了pcl启动器 这次连optfine都没装 好像跟forge也没关系 同样也有问题 我的java是17.0.3 我升级试试

另外就是我用的java是jdk 不知道会不会有影响

**Comment by JesKi13567** [comment]
终于我也测出来bug了，我用1.19.3原版端反复进出最后也不显示了，我去加个针对单人的暂停键或者恢复键吧。

**Comment by rmm233** [comment]
好嘚 辛苦老哥了

**Comment by JesKi13567** [comment]
现在用1.2.1版本试试，如果消失就选择一下。

**Comment by JesKi13567** [comment]
现在用1.2.1版本试试，如果消失就选择一下。

**Comment by rmm233** [comment]
> 现在用1.2.1版本试试，如果消失就选择一下。

可以了！还有10s的时间补偿 贴心啊2333333

**Comment by JesKi13567** [comment]
嗯哼能用就行了。
